{% set name = "rectangularprismviewer" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Beeram12/RectangularPrismViewer.git
  git_tag: main

build:
  number: 0
  script: "./build.sh"

requirements:
  build:
    - python>=3.10
    - setuptools
  run:
    - python 

test:
  imports:
    - test_prism_calculator
    - main  

about:
  home: https://github.com/Beeram12/RectangularPrismViewer.git
  license: MIT
  license_family: MIT
  summary: "A viewer and calculator for rectangular prism properties"
